### ISSUE TITLE
Use Cryptographic Node Identifiers

### ISSUE THREAD

**Issue by bonedaddy** [lnx-search/datacake#13]
# Overview

Right now node identifiers are simple strings, and it could be easy to misconfigure a datacake cluster to duplicate node identifiers, etc.. which as the warnings advise would effect the ability of the cluster to reach consistency. Additionally misconfigured firewall rules could make it easy for an attacker to cause cluster consistency issues by simply creating duplicate nodes.

# Solution

Using public key cryptography, one can construct node identifiers using the public key, and messages sent by the cluster member are signed by the corresponding private key. This prevents simple misconfiguration issues of duplicate node identifiers, but also provide the ground work for adding more advanced features which I'll detail below.

# Advanced Features

## Read Only / Mirror Cluster Members

Right now (if i understand the codebase correctly) every cluster member has equal rights, which means it's not possible to add cluster members that are read-only and unable to broadcast state changes.  For datacake deployments with high security requirements, one may only want state changes to be able to come from 1->2 nodes, while being able to replicate to 3->5 nodes.

By using cryptographic node identifiers, any state changes that are signed by an authorized keypair can be rejected.

## Keyspace Based Access Control

With cryptographic identifiers,  one has the ability to specify access controls to specific keyspaces. For example state changes signed by node `A` within the `foo` keyspace are permitted, but a state change signed by node `A` within the `baz` keyspace is denied.

**Comment by ChillFish8** [comment]
This is realistically out of the scope of datacake as a library I feel, although maybe it should be made clear in the docs that datacake is *not* designed to be exposed to any sort of public network.

> Right now node identifiers are simple strings, and it could be easy to misconfigure a datacake cluster to duplicate node identifiers, etc.. which as the warnings advise would effect the ability of the cluster to reach consistency.

To expand on this, a node joining the same cluster with the same ID as an existing cluster member, will just not be noticed by the cluster, it may be able to join, but it wont register as a membership change. The issue isn't around nodes joining the cluster with the same ID, it's an issue of it causing divergence within the core state itself, this is because it no longer ensures causality or partial ordering.

>Using public key cryptography, one can construct node identifiers using the public key, and messages sent by the cluster member are signed by the corresponding private key. This prevents simple misconfiguration issues of duplicate node identifiers, but also provide the ground work for adding more advanced features which I'll detail below.

The main issue I have with this is as follows:
- This adds a significant amount of technical load to using the library, since each node you spawn now would need to keep and persist it's own node id that's generated. - If you don't you will never purge tombstones from the memory state.
- This doesn't actually prevent a malicious node or attacker alter the cluster state if the cluster is not secured behind a firewall or other security system. It just stops the node trying to gossip, which isn't really as big of a deal as the ability to register operations or read repairs as if you were the node, not for the fact that executing un authorized ops are bad, but because it'll push the state's observed timestamp forward meaning events can potentially be ignored.

> Right now (if i understand the codebase correctly) every cluster member has equal rights, which means it's not possible to add cluster members that are read-only and unable to broadcast state changes. For datacake deployments with high security requirements, one may only want state changes to be able to come from 1->2 nodes, while being able to replicate to 3->5 nodes.
> By using cryptographic node identifiers, any state changes that are signed by an authorized keypair can be rejected.

IMO this is not datacake's job to provide this, I considered it, but fundamentally read only replicas should be managed by what ever system is using datacake, the difference between a read only replica and a writer would just be if something has a handle to the node or not, everything else would have to stay the same.

> With cryptographic identifiers, one has the ability to specify access controls to specific keyspaces. For example state changes signed by node A within the foo keyspace are permitted, but a state change signed by node A within the baz keyspace is denied.

Again, I think this is out of scope for datacake, it's easier to implement this on what ever thing is using datacake rather than datacake itself, one could simply just filter out specific keyspaces when performing operations on the node.

**Comment by bonedaddy** [comment]
Makes sense, thanks for the very detailed explanation.
