### ISSUE TITLE
Thoughts on adding application metadata?

### ISSUE THREAD

**Issue by ltransom** [lnx-search/datacake#51]
I am looking at writing an application using datacake and it would be very useful to store additional metadata for the documents.

Based on my review of the code, it looks like the current implementation of the various components only supports the three existing metadata items.  I did not see a way to easily extend the implementations to add metadata items.

My first question is make sure I am understanding the code correctly and I am not missing a way to extend.

If customers metadata items are unsupported today, have you contemplated an approach to enabling it?

**Comment by ChillFish8** [comment]
The general idea is your document data should include everything you need, since it's just a blob of data you can store anything in it really and it'll be handled with everything else.

I agree to have a dedicated field for those sorts of things might be fairly convenient, but I think it's just cutting the small step of slicing the data or adjusting how you (de)serialize the blob of data.

**Comment by ltransom** [comment]
The challenge is that it is not necessarily a small step.  It would be costly to perform a scan of the metadata cross the keyspace if the document size is large in relation to the few pieces of small metadata, since the entirety of the document would need to be retrieved to just then slice off a piece.

In the existing consistency layer, imagine needing to load the entire document blob just to find the timestamp or tombstone status.  My use case is similar, so I really cannot bundle my metadata with the document, it would utterly devastate performance for what I need to do.

I think you all have started an amazing project.  I guess part of what I am feeling out is where you want to go with this project.  Is this something where you are wanting to open up contributions, both architectural and implementation, or are you more in the space of wanting it to primarily fulfill your needs.  BTW, I am not offended by the answer either way, just trying to understand.

Also for clarity, this is not something that I am just opening a feature request to put work on somebody else.  I am trying to gauge whether I just take on the work internally for my needs, try to orchestrate a solution here, or find a reasonable way to workaround.

Your idea of having a general purpose metadata field seems relatively straightforward.

Anyway, I appreciate your time, efforts, and thoughts.

**Comment by ChillFish8** [comment]
*ah* Sorry I thought you meant more in terms of the `Document` structure rather than storage of the data...

The reason why metadata like the tombstone and timestamp is recommended to be bundled with the data for the existing `Storage` implementations is that it's a defensive design choice.

Since the timestamp and tombstone indicator are *incredibly* important for maintaining correctness, the API is designed so it's up to the user to decide if they want to store it separately to the main blob of data, or as one.

This is because you must ensure the whole operation is atomic, and it's very easy to get wrong or be misled by the API if it had two methods for setting metadata and setting the blob. Technically the KV store just cannot do two separate methods because in the event one fails and the other doesn't, it cannot reset the state correctly.

If your goal is storing the metadata and data in separate databases for example, then yes, you can do that and it won't affect anything as long at the overall operation being performed is atomic (So you're not left with some metadata being written but the blob of data not being written)

**Comment by ChillFish8** [comment]
to add to the extending part as well in a bit more detail (Sorry I'm a bit all over the place with this discussion) 

It's possible that you can send the additional metadata combined with the document data just for the RPC process, and then store it separately.

Unfortunately, it is probably going to lead to additional allocation, which is probably more of an issue *sending* the data rather than receiving if you use the `Document` type, which will be improved eventually, but I think it requires some custom handling of rkyv that just isn't done currently.

Another possible thing you can do is make another RPC service which ships the main blob of data, and then your `Document` which is replicated directly is just the metadata. This is probably the approach i'd go with if I was making something like a blob store.

**Comment by ltransom** [comment]
I appreciate all of your thoughts and considerations.  I need to think about what is the best approach given my application needs.

I had not really thought about the idea of creating a separate RPC service for blob data.  I was heading more down the path of the two separate databases for metadata and data.

My data is heterogenous: JSON, XML, CSV, KML, KMZ, shape files, imagery, Parquet, Arrow, model files, etc.  Stated differently, my application views all of these types as first class citizens.

**Comment by ChillFish8** [comment]
I think for that application a secondary RPC service is probably best -> It'll be more optimised since you can get a zero-copy view of the data rather than paying for the allocation.

This is actually designed to make your life quite easy since you can use the `put_with_ctx` methods in the `Storage` trait to get access to the remote server's RPC address to contact the second service.

**Comment by ltransom** [comment]
Thank you again for your thoughts.  I am closing this as I have enough to go on from here.
