### ISSUE TITLE
Ability to get a list of keyspaces and keys from datacake_eventual_consistency

### ISSUE THREAD

**Issue by ltransom** [lnx-search/datacake#54]
The underlying Storage trait requires the `get_keyspace_list` and the `iter_metadata` methods.  However, these methods are not exposed to an application using `datacake_eventual_consistency`.

Is this an intentional design choice, am I missing the intended way to access the list of keyspaces and keys from the underlying storage, or is this something that needs to be built out?

**Comment by ltransom** [comment]
My intent is provide to new public methods in the eventual consistency layer to allow applications using the layer to discover the available keyspaces and keys.

After reviewing the associated underlying code, it seemed most prudent not to expose an iterator of the metadata.

After reviewing other implementations of similar systems, the typical approach is to return a collection of the keys.

**Comment by ChillFish8** [comment]
> Is this an intentional design choice, am I missing the intended way to access the list of keyspaces and keys from the underlying storage, or is this something that needs to be built out?

The methods are more for the internals of datacake rather than for a publically accessible API. They're there so datacake can recreate its internal memory state.

The only reason why I'm somewhat hesitant to expose these methods is because they can't give you the 'full' list potentially, they can only give you the state that it's aware of locally rather than across the whole cluster. 

Another thing to mention (maybe it's worth improving the docs on;) is that keyspaces should be fairly static rather than dynamically adding them. Although it's not necessarily bad, you can't remove keyspaces once they're made, and past a certain point, you probably limit your performance quite heavily (In the event of there being millions of keyspaces).

For example in lnx there are effectively 4 static keyspaces:

- `metadata/config`
- `schemas/settings`
- `schemas/schema`
- `data/doc-blocks`

Now in reality there are technically more of these keyspaces because each keyspace is effectively one concurrent lane, so if you have say `12` keyspaces, you can do up to 12 operations concurrently if you split the data across them.

So in lnx's case it has 128 `data/doc-block` keyspaces to maximise its replication speed, but these are fixed and aren't added dynamically because technically you can end up in a situation where the number of keyspaces just increases forever.

I may be able to improve this in later versions if the state is completely empty, we can probably remove the keyspace from the internal state. But this is quite rare in normal situations.
